version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

      - name: FName
        description: "The First Name of the Student"
        tests:
          - not_null

      - name: LName
        description: "The Last Name of the Student"
        tests:
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: FName
        description: "The First Name of the Student"
        tests:
          - not_null

      - name: LName
        description: "The Last Name of the Student"
        tests:
          - not_null
